ALTER TABLE parishes ADD COLUMN IF NOT EXISTS display_interval_seconds INTEGER DEFAULT 5;
ALTER TABLE parishes ADD COLUMN IF NOT EXISTS display_names_per_page INTEGER DEFAULT 5;
ALTER TABLE parishes ADD COLUMN IF NOT EXISTS display_columns INTEGER DEFAULT 1;
ALTER TABLE parishes ADD COLUMN IF NOT EXISTS display_bg_image TEXT;
ALTER TABLE parishes ADD COLUMN IF NOT EXISTS display_bg_fit VARCHAR DEFAULT 'fill';
ALTER TABLE parishes ADD COLUMN IF NOT EXISTS display_font_family VARCHAR DEFAULT 'Georgia';
ALTER TABLE parishes ADD COLUMN IF NOT EXISTS display_font_size INTEGER DEFAULT 0;
ALTER TABLE parishes ADD COLUMN IF NOT EXISTS display_font_bold BOOLEAN DEFAULT FALSE;
ALTER TABLE parishes ADD COLUMN IF NOT EXISTS display_text_case VARCHAR DEFAULT 'original';
